config/routes.rb
Rails.application.routes.draw do
  
  root 'employees#index'
  resources :employees, :doctors, :patients, :appointments

  get 'appointments/index'

  get 'patients/index'

  get 'doctors/index'

  get 'employees/index'

  get '/appointments_dr/:id', to: 'appointments#appos', as: 'appointment_of_doctor'

  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :supplier
	has_one :account_history
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
	belongs_to :account

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

	belongs_to :doctor
	belongs_to :patient


 

end

app/models/assembly.rb
class Assembly < ApplicationRecord
	has_and_belongs_to_many :parts
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :appointments
	has_many :patients, through: :appointments	
	validates :name, presence: true
	validates :name, format: {with: /\A[a-zA-Z]+\z/, message: 'only alphabets are permitted'}
	validates :name, length: {minimum: 5, maximum: 25, message: 'Name must be of 5 to 25 characters'}
	
end

app/models/employee.rb
class Employee < ApplicationRecord

	validates :Name, :Mobile, :email, :password, :password_confirmation, presence: true
	validates :Name, format: {with: /\A[a-zA-Z]+\z/, message: 'only alphabets are permitted'}
	validates :Mobile, numericality: true
	validates :Name, length: {minimum: 5, maximum: 25, message: 'Name must be of 5 to 25 characters'}
	validates :password, confirmation: true

end

app/models/engineer.rb
class Engineer < ApplicationRecord
	has_many :subordinates, class_name: "Engineer", foreign_key: "senior_id"
	belongs_to :senior, class_name: "Engineer", required: false

end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :imageable, polymorphic: true
end

app/models/part.rb
class Part < ApplicationRecord
	has_and_belongs_to_many :assemblies
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
	has_many :doctors, through: :appointments		
	validates :name, presence: true
	validates :name, format: {with: /\A[a-zA-Z]+\z/, message: 'only alphabets are permitted'}
	validates :name, length: {minimum: 5, maximum: 25, message: 'Name must be of 5 to 25 characters'}
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :images, as: :imageable
end

app/models/supplier.rb
class Supplier < ApplicationRecord
has_one :account
has_one :account_history, through: :account
end

app/models/user.rb
class User < ApplicationRecord
	has_many :images, as: :imageable
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
  	@doctors = Doctor.all
  end
 
  def new
		@doctor = Doctor.new
  end

	def create
		@doctor = Doctor.new(get_params)
 
  	@doctor.save
  	if @doctor.save
    	redirect_to @doctor
  	else
    	render 'new'
  	end
  end

	def show
		@doctor = Doctor.find(params[:id])
  end

	def edit
		@doctor = Doctor.find(params[:id])
  end

	def update
		@doctor = Doctor.find(params[:id])
 
  if @doctor.update(get_params)
    redirect_to @doctor
  else
    render 'edit'
  end
  end

	def destroy
		 @doctor = Doctor.find(params[:id])
   @doctor.destroy
 		 redirect_to doctors_path
 	
  end	  

  def get_params
params.require(:doctor).permit(:name)
  end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
  	@employee = Employee.all
  end

	def new
		@employee = Employee.new
  end

	def create
		@employee = Employee.new(get_params)
 
  	@employee.save
  	if @employee.save
    	redirect_to @employee
  	else
    	render 'new'
  	end
  end

	def show
		@employee = Employee.find(params[:id])
  end

	def edit
		@employee = Employee.find(params[:id])
  end

	def update
		@employee = Employee.find(params[:id])
 
  if @employee.update(get_params)
    redirect_to @employee
  else
    render 'edit'
  end
  end

	def destroy
		 @employee = Employee.find(params[:id])
   @employee.destroy
 		 redirect_to employees_path
 	
  end	  

  def get_params
params.require(:employee).permit(:Name, :Mobile, :email, :password, :password_confirmation)
  end

		  
	  
	  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/employees/_forms.html.erb
<%= form_with model: @employee, local: true do |form| %>
 
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee.errors.count, "error") %> prohibited
        this employee details from being saved:
      </h2>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :Name %>
  </p>
 
  <p>
    <%= form.label :Mobile %><br>
    <%= form.text_field :Mobile %>
  </p>
 
 <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

 <p>
    <%= form.label :Password %><br>
    <%= form.password_field :password %>
  </p>

   <p>
    <%= form.label :Confirm_password %><br>
    <%= form.password_field :password_confirmation %>
  </p>



  <p>
    <%= form.submit %>
  </p>
 
<% end %> 

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>
 
<%= render 'forms' %>
 
<%= link_to 'Back', employee_path %>

app/views/employees/index.html.erb
<h1>Listing All Employees</h1>
<p><%= link_to 'New Employee', new_employee_path %></p>
<p><%= link_to 'All Doctors', doctors_path %></p>
<p><%= link_to 'All patients', patients_path %></p>
<p><%= link_to 'All Appointments', appointments_path %></p> 
<p><%= link_to 'New Appointments', new_appointment_path %></p> 
 

<table border = "1">
  <tr>
    <th ><b>Id</b></th>
    <th ><b>Name</b></th>
    <th ><b>Mobile</b></th>
    <th ><b>email</b></th>
  <th ><b>Action</b></th>
  </tr>
 
  <% @employee.each do |employee| %>
    <tr>
      <td><%= employee.id %></td>
      <td><%= employee.Name %></td>
      <td><%= employee.Mobile %></td>
      <td><%= employee.email %></td>
      <td><%= link_to 'Show', employee_path(employee) %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'Edit', edit_employee_path(employee) %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'Delete', employee_path(employee),method: :delete,data: { confirm: 'Are you sure?' }%>

      </td>
    </tr>
  <% end %>
</table>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'forms' %>
<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<h1>Employee Data</h1>


<p>
  <strong>Name:</strong>
  <%= @employee.Name %>
</p>
 
<p>
  <strong>Mobile:</strong>
  <%= @employee.Mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>


<p>
<%= link_to 'Edit', edit_employee_path(@employee) %>

</p>

<%= link_to 'Index', employees_path %>