config/routes.rb
Rails.application.routes.draw do
  
  root 'employees#index'
  resources :employees, :doctors, :patients, :appointments

  get 'appointments/index'

  get 'patients/index'

  get 'doctors/index'

  get 'employees/index'

  get '/appointments_dr/:id', to: 'appointments#appos', as: 'appointment_of_doctor'

  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :supplier
	has_one :account_history
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
	belongs_to :account

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

	belongs_to :doctor
	belongs_to :patient


 

end

app/models/assembly.rb
class Assembly < ApplicationRecord
	has_and_belongs_to_many :parts
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :appointments
	has_many :patients, through: :appointments	
	validates :name, presence: true
	validates :name, format: {with: /\A[a-zA-Z]+\z/, message: 'only alphabets are permitted'}
	validates :name, length: {minimum: 5, maximum: 25, message: 'Name must be of 5 to 25 characters'}
	
end

app/models/employee.rb
class Employee < ApplicationRecord

	validates :Name, :Mobile, :email, :password, :password_confirmation, presence: true
	validates :Name, format: {with: /\A[a-zA-Z]+\z/, message: 'only alphabets are permitted'}
	validates :Mobile, numericality: true
	validates :Name, length: {minimum: 5, maximum: 25, message: 'Name must be of 5 to 25 characters'}
	validates :password, confirmation: true

end

app/models/engineer.rb
class Engineer < ApplicationRecord
	has_many :subordinates, class_name: "Engineer", foreign_key: "senior_id"
	belongs_to :senior, class_name: "Engineer", required: false

end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :imageable, polymorphic: true
end

app/models/part.rb
class Part < ApplicationRecord
	has_and_belongs_to_many :assemblies
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
	has_many :doctors, through: :appointments		
	validates :name, presence: true
	validates :name, format: {with: /\A[a-zA-Z]+\z/, message: 'only alphabets are permitted'}
	validates :name, length: {minimum: 5, maximum: 25, message: 'Name must be of 5 to 25 characters'}
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :images, as: :imageable
end

app/models/supplier.rb
class Supplier < ApplicationRecord
has_one :account
has_one :account_history, through: :account
end

app/models/user.rb
class User < ApplicationRecord
	has_many :images, as: :imageable
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
  	@doctors = Doctor.all
  end
 
  def new
		@doctor = Doctor.new
  end

	def create
		@doctor = Doctor.new(get_params)
 
  	@doctor.save
  	if @doctor.save
    	redirect_to @doctor
  	else
    	render 'new'
  	end
  end

	def show
		@doctor = Doctor.find(params[:id])
  end

	def edit
		@doctor = Doctor.find(params[:id])
  end

	def update
		@doctor = Doctor.find(params[:id])
 
  if @doctor.update(get_params)
    redirect_to @doctor
  else
    render 'edit'
  end
  end

	def destroy
		 @doctor = Doctor.find(params[:id])
   @doctor.destroy
 		 redirect_to doctors_path
 	
  end	  

  def get_params
params.require(:doctor).permit(:name)
  end


end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
  	@patients = Patient.all
  end

  def new
		@patient = Patient.new
  end

	def create
		@patient = Patient.new(get_params)
 
  	@patient.save
  	if @patient.save
    	redirect_to @patient
  	else
    	render 'new'
  	end
  end

	def show
		@patient = Patient.find(params[:id])
  end

	def edit
		@patient = Patient.find(params[:id])
  end

	def update
		@patient = Patient.find(params[:id])
 
  if @patient.update(get_params)
    redirect_to @patient
  else
    render 'edit'
  end
  end

	def destroy
		 @patient = Patient.find(params[:id])
   @patient.destroy
 		 redirect_to patients_path
 	
  end	  

  def get_params
params.require(:patient).permit(:name)
  end

		  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/_forms.html.erb
<%= form_with model: @doctor, local: true do |form| %>
 
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@doctor.errors.count, "error") %> prohibited
        this doctor details from being saved:
      </h2>
      <ul>
        <% @doctor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>
 
  


  <p>
    <%= form.submit %>
  </p>
 
<% end %> 

app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>
 
<%= render 'forms' %>
 
<%= link_to 'Back', employee_path %>

app/views/doctors/index.html.erb
<h1>Listing All Doctors</h1>
<!-- <p><%= link_to 'New Employee', new_employee_path %></p> -->
<p><%= link_to 'Index', employees_path %></p>
<p><%= link_to 'New Doctor', new_doctor_path %></p>
<table border = "1">
  <tr>
    <th ><b>Id</b></th>
    <th ><b>Name</b></th>
    
  <th ><b>Action</b></th>
  </tr>
 
  <% @doctors.each do |doctor| %>
    <tr>
      <td><%= doctor.id %></td>
      <td><%= doctor.name %></td>
    
      <td><%= link_to 'Show', doctor_path(doctor) %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'Edit', edit_doctor_path(doctor) %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'Delete', doctor_path(doctor),method: :delete,data: { confirm: 'Are you sure?' }%>
&nbsp;&nbsp;&nbsp;
      <%= link_to 'Appointments', appointment_of_doctor_path(doctor) %>

      </td>
    </tr>
  <% end %>
</table>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'forms' %>
<%= link_to 'Back', employees_path %>

app/views/doctors/show.html.erb
<h1>Doctor Data</h1>


<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>
 


<p>
<%= link_to 'Edit', edit_doctor_path(@doctor) %>

</p>

<%= link_to 'Index', employees_path %>

app/views/patients/_forms.html.erb
<%= form_with model: @patient, local: true do |form| %>
 
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@patient.errors.count, "error") %> prohibited
        this patient details from being saved:
      </h2>
      <ul>
        <% @patient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>
 



  <p>
    <%= form.submit %>
  </p>
 
<% end %> 

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>
 
<%= render 'forms' %>
 
<%= link_to 'Back', employee_path %>

app/views/patients/index.html.erb
<h1>Listing All Patients</h1>
<!-- <p><%= link_to 'New Employee', new_employee_path %></p> -->
<p><%= link_to 'Index', employees_path %></p>
<p><%= link_to 'New Patient', new_patient_path %></p>
<table border = "1">
  <tr>
    <th ><b>Id</b></th>
    <th ><b>Name</b></th>
    
  <th ><b>Action</b></th>
  </tr>
 
  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.id %></td>
      <td><%= patient.name %></td>
      <td><%= link_to 'Show', patient_path(patient) %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'Edit', edit_patient_path(patient) %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'Delete', patient_path(patient),method: :delete,data: { confirm: 'Are you sure?' }%>

      </td>
    </tr>
  <% end %>
</table>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'forms' %>
<%= link_to 'Back', employees_path %>

app/views/patients/show.html.erb
<h1>Patient Data</h1>


<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>
 



<p>
<%= link_to 'Edit', edit_patient_path(@patient) %>

</p>

<%= link_to 'Index', employees_path %>