config/routes.rb
Rails.application.routes.draw do
  
  root 'employees#index'
  resources :employees, :doctors, :patients, :appointments

  get 'appointments/index'

  get 'patients/index'

  get 'doctors/index'

  get 'employees/index'

  get '/appointments_dr/:id', to: 'appointments#appos', as: 'appointment_of_doctor'

  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :supplier
	has_one :account_history
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
	belongs_to :account

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

	belongs_to :doctor
	belongs_to :patient


 

end

app/models/assembly.rb
class Assembly < ApplicationRecord
	has_and_belongs_to_many :parts
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :appointments
	has_many :patients, through: :appointments	
	validates :name, presence: true
	validates :name, format: {with: /\A[a-zA-Z]+\z/, message: 'only alphabets are permitted'}
	validates :name, length: {minimum: 5, maximum: 25, message: 'Name must be of 5 to 25 characters'}
	
end

app/models/employee.rb
class Employee < ApplicationRecord

	validates :Name, :Mobile, :email, :password, :password_confirmation, presence: true
	validates :Name, format: {with: /\A[a-zA-Z]+\z/, message: 'only alphabets are permitted'}
	validates :Mobile, numericality: true
	validates :Name, length: {minimum: 5, maximum: 25, message: 'Name must be of 5 to 25 characters'}
	validates :password, confirmation: true

end

app/models/engineer.rb
class Engineer < ApplicationRecord
	has_many :subordinates, class_name: "Engineer", foreign_key: "senior_id"
	belongs_to :senior, class_name: "Engineer", required: false

end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :imageable, polymorphic: true
end

app/models/part.rb
class Part < ApplicationRecord
	has_and_belongs_to_many :assemblies
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
	has_many :doctors, through: :appointments		
	validates :name, presence: true
	validates :name, format: {with: /\A[a-zA-Z]+\z/, message: 'only alphabets are permitted'}
	validates :name, length: {minimum: 5, maximum: 25, message: 'Name must be of 5 to 25 characters'}
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :images, as: :imageable
end

app/models/supplier.rb
class Supplier < ApplicationRecord
has_one :account
has_one :account_history, through: :account
end

app/models/user.rb
class User < ApplicationRecord
	has_many :images, as: :imageable
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
  	@appointments = Appointment.all
  	@doctors = Doctor.all
  	@patients = Patient.all
  end

  def appos
		@appointments = Appointment.where(doctor_id: params[:id])
		
		# redirect_to appointment_of_doctor_path(params[:id])

  end

def new
	@appointment = Appointment.new

end


	def create
		@dr = Doctor.find(params[:appointment][:doctor_id])
 
  	if @dr.appointments.create(patient_id: params[:appointment][:patient_id],appointment_date: params[:appointment][:appointment_date],appointment_time: params[:appointment][:appointment_time])
#      exit
  	 redirect_to employees_path
    else
      render 'new'
    end


  	end
  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
 
  if @appointment.update(get_params)
    redirect_to appointments_path
  else
    render 'edit'
  end
  end

  def destroy
     @appointment = Appointment.find(params[:id])
   @appointment.destroy
     redirect_to appointments_path
  
  end   


	
 def get_params
params.require(:appointment).permit(:doctor_id, :patient_id, :appointment_date, :appointment_time)
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
  	@doctors = Doctor.all
  end
 
  def new
		@doctor = Doctor.new
  end

	def create
		@doctor = Doctor.new(get_params)
 
  	@doctor.save
  	if @doctor.save
    	redirect_to @doctor
  	else
    	render 'new'
  	end
  end

	def show
		@doctor = Doctor.find(params[:id])
  end

	def edit
		@doctor = Doctor.find(params[:id])
  end

	def update
		@doctor = Doctor.find(params[:id])
 
  if @doctor.update(get_params)
    redirect_to @doctor
  else
    render 'edit'
  end
  end

	def destroy
		 @doctor = Doctor.find(params[:id])
   @doctor.destroy
 		 redirect_to doctors_path
 	
  end	  

  def get_params
params.require(:doctor).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_forms.html.erb
<%= form_with model: @appointment, local: true do |form| %>
 
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@appointment.errors.count, "error") %> prohibited
        this appointment details from being saved:
      </h2>
      <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :Select_Doctor %><br>
    <%= form.collection_select :doctor_id, Doctor.order(:id), :id, :name %>
  </p>
 
  <p>
    <%= form.label :Select_Patient %><br>
    <%= form.collection_select :patient_id, Patient.order(:id), :id, :name %>
  </p>
 
 <p>
    <%= form.label :Appointment_Date %><br>
    <%= form.date_field :appointment_date, min: Date.today %>
  </p>

 <p>
    <%= form.label :Appointment_Time %><br>
    <%= form.time_field :appointment_time, min: Time.now %>
  </p>

  


  <p>
    <%= form.submit %>
  </p>
 
<% end %> 

app/views/appointments/appos.html.erb
<h1>Listing All Appointments</h1>
<!-- <p><%= link_to 'New Employee', new_employee_path %></p> -->
<p><%= link_to 'Index', employees_path %></p>
<table border = "1">
  <tr>
    <th ><b>Id</b></th>
    <th ><b>Doctor</b></th>
    <th ><b>Patient</b></th>
    <th ><b>Date</b></th>
    <th ><b>Time</b></th>
	<th ><b>Action</b></th>
  </tr>
 
  <% @appointments.each do |appointment| %>
    <tr>
    	<td><%= appointment.id %></td>
      <td><%= appointment.doctor_id %></td>
      <td><%= appointment.patient_id %></td>
      <td><%= appointment.appointment_date %></td>
      <td><%= appointment.appointment_time %></td>
      
      <td>
      <%= link_to 'Edit', edit_appointment_path(appointment) %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'Delete', appointment_path(appointment),method: :delete,data: { confirm: 'Are you sure?' }%>

      </td>
    </tr>
  <% end %>
</table>

app/views/appointments/edit.html.erb
<h1>Edit Appointments</h1>
 
<%= render 'forms' %>
 
<%= link_to 'Back', appointment_path %>

app/views/appointments/index.html.erb
<h1>Listing All Appointments</h1>
<!-- <p><%= link_to 'New Employee', new_employee_path %></p> -->
<p><%= link_to 'Index', employees_path %></p>
<table border = "1">
  <tr>
    <th ><b>Id</b></th>
    <th ><b>Doctor</b></th>
    <th ><b>Patient</b></th>
    <th ><b>Date</b></th>
    <th ><b>Time</b></th>
	<th ><b>Action</b></th>
  </tr>
 
  <% @appointments.each do |appointment| %>
    <tr>
    	<td><%= appointment.id %></td>
      <td><%= appointment.doctor_id %></td>
      <td><%= appointment.patient_id %></td>
      <td><%= appointment.appointment_date %></td>
      <td><%= appointment.appointment_time %></td>
      
      <td><%= link_to 'Show', appointment_path(appointment) %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'Edit', edit_appointment_path(appointment) %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'Delete', appointment_path(appointment),method: :delete,data: { confirm: 'Are you sure?' }%>

      </td>
    </tr>
  <% end %>
</table>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'forms' %>
<%= link_to 'Back', employees_path %>